### ISSUE TITLE
Métodos consultarMovimentos em models/Conta.java

### ISSUE THREAD

**Issue by itsshimmer** [pucrs-gcs-2020-1/trabalho1-20201-artesaos_group#10]
Respeitar filtros descritos no diagrama

**Comment by FranciscoJLucca** [comment]
O método de _consultaMovimentos(Operador)_ não deveria ser feito na classe de gerenciadores ? Por que sendo feito na classe _Conta_ o operador será único, não ?

**Comment by itsshimmer** [comment]
Acho que segundo o enunciado ele quer filtrar na Conta selecionada os movimentos por Operador, já que operadores diferentes podem operar na mesma conta, e também há depósitos vindo de outras contas.
![image](https://user-images.githubusercontent.com/34427420/82738209-6487a100-9d0c-11ea-82e5-5b66e5ab7dad.png)
@soares-eduardo dá uma olhada aí e vê o que acha

**Comment by soares-eduardo** [comment]
Nesse caso, concordo com o @FranciscoJLucca. Especificando melhor a feature, ele quer todos os movimentos de um operador, logo teriamos que percorrer o array de contas procurando pelo operador informado e então descarregar todas as suas movimentações.

**Comment by itsshimmer** [comment]
@FranciscoJLucca realmente vc estava correto, foi feito um hotfix e enviado para pull request, basta fazer review e dar merge https://github.com/pucrs-gcs-2020-1/trabalho1-20201-artesaos_group/pull/15
