### ISSUE TITLE
Movimentação deve Receber Operador

### ISSUE THREAD

**Issue by oliveirafilipe** [pucrs-gcs-2020-1/trabalho1-20201-artesaos_group#13]
Ao criar uma operação, ela deve receber o operador que está realizando esta operação.

É possível verificar que uma operação possui operador ao consultarmos o relátorio de exemplo:

![image](https://user-images.githubusercontent.com/22033274/82771773-7a33be00-9e13-11ea-82a7-61a329a4f78c.png)

Mesma conta, vários operadores

**Comment by itsshimmer** [comment]
Acessar https://github.com/pucrs-gcs-2020-1/trabalho1-20201-artesaos_group/pull/15 e fazer o review e merge, assim já poderá dar continuidade.
